---
-
  name: "Staff"
  id: "staff"
-
  name: "Color"
  id: "color"
-
  name: "Age"
  id: "age"
-
  name: "Access / Status"
  id: "status"
-
  name: "Membership"
  id: "membership"
-
  name: "Activity Level"
  id: "activity"
-
  name: "Notification Preference"
  id: "notification"
-
  name: "Direct Message Preference"
  id: "dm"
-
  name: "Pronouns"
  id: "pronouns"
-
  name: "Identities"
  id: "identity"
-
  name: "Sun Sign"
  id: "zodiac"
-
  name: "MBTI"
  id: "mbti"
-
  name: "Enneagram (Base)"
  id: "enneagram"
-
  name: "Enneagram (Wing)"
  id: "wing"
-
  name: "Enneagram (Subtype)"
  id: "instinct"
-
  name: "Element"
  id: "element"
-
  name: "Hogwarts House"
  id: "hogwarts"
-
  name: "Languages"
  id: "language"
-
  name: "Entities"
  id: "entity"
-
  name: "Beliefs / Paths"
  id: "belief"
-
  name: "Polytheism"
  id: "polytheism"
-
  name: "Disciplines"
  id: "discipline"
---
