---
-
  type: "text"
  category: "Introduction"
  text: "Welcome to <code>The Night House | בית הלילה</code>!"
-
  type: "text"
  category: "Introduction"
  text: "To gain access to the main part of the server, you will need to request the !@!497610586750976020!@! role from a !@!499037360340598819!@! member in the !#!role-request!#! channel."
-
  type: "text"
  category: "Introduction"
  text: "In that channel you may also optionally self assign a number of roles, listed out below. The roles that can be self assigned have <span class=\"b\">clickable green buttons</span> which, when pressed, will copy the role assignment command to your system clipboard so that you can easily paste it in the channel."
-
  type: "text"
  category: "Introduction"
  text: "<span class=\"b\">Please only paste and send one command at a time</span>. The bot does not know how to parse more than one command per message."
-
  type: "note"
  category: "Introduction"
  text: "Example: <code>n.iam <@&504966239765135360></code> would <span class=\"i\">assign</span> you to the !@!504966239765135360!@! role."
-
  type: "text"
  category: "Introduction"
  text: "To unassign a self-assigned role, use the same command but replace <code>n.iam</code> with <code>n.iamn</code>."
-
  type: "note"
  category: "Introduction"
  text: "Example: <code>n.iamn <@&504966239765135360></code> would <span class=\"i\">unassign</span> you from the !@!504966239765135360!@! role."
-
  type: "text"
  category: "Introduction"
  text: "When you get the opportunity, please also <span class=\"b\">leave a quick introduction</span> in the !#!introduction!#! channel. In addition to learning more about you and your practice, we'd also like to know how you found us!"
-
  type: "role"
  category: "Staff"
  name: "Administrator | כוהנת"
  id: "497584935234830366"
  color: "#e4b400"
  text: "this is my admin role, and the Hebrew means \"priestess\" [cohenet]."
  show_button: false
-
  type: "role"
  category: "Staff"
  name: "Moderators | מנהלים"
  id: "497580616817311745"
  color: "#ff7503"
  text: "this is the role for our most trusted, senior moderators, who must be over the age of 18 (legal majority). The Hebrew means \"moderators\" [menahelim]."
  show_button: false
-
  type: "role"
  category: "Staff"
  name: "Assistant Moderators | עוזר מנהלים"
  id: "499033497764233237"
  color: "#b4570f"
  text: "this is the role for assistant/junior moderators, who may be under 18 provided that they are sufficiently trustworthy to handle such duties. The Hebrew means \"assistant moderators\" [ozer menahelim]."
  show_button: false
-
  type: "role"
  category: "Staff"
  name: "Staff | צוות"
  id: "499037360340598819"
  color: "#8c0cc5"
  text: "this role is for server staff, so when you need help with something you can ping this role and everyone who helps manage the server will get pinged, rather than just one tier of moderators. The Hebrew means \"staff\" [tzevet]."
  show_button: false
-
  type: "role"
  category: "General"
  name: "Members | חברים"
  id: "497610586750976020"
  color: "#17ac86"
  text: "this is a general role for server members, and it is required to access the main part of the server. The Hebrew simply means \"members\" [khaverim]."
  show_button: false
-
  type: "role"
  category: "General"
  name: "Bots | רובוטים"
  id: "497626822742376448"
  color: "#808588"
  text: "Bots"
  show_button: false
-
  type: "role"
  category: "General"
  name: "Guests | אורחים"
  id: "504828346522140693"
  color: "#4d6875"
  text: "this role is auto assigned to server members when they join. It is a temporary role denoting that a user lacks access to the main part of the server, and will be removed and replaced with the Members role once the user demonstrates sufficient initiative / humanity to be admitted to the server (i.e. reading the !#!rules!#! and !#!roles!#!, leaving an !#!introduction!#!, and visiting !#!role-request!#! to ask for roles. The Hebrew means \"guests\" [orkhim]."
  show_button: false
-
  type: "note"
  category: "Messaging Preferences"
  text: "Note: these roles are not relevant for server staff since they are here to help you if you need anything, so feel free to DM !@!499037360340598819!@! if you need assistance."
-
  type: "role"
  category: "Messaging Preferences"
  name: "Notify | להודיע"
  id: "504966239765135360"
  color: "#1a7939"
  text: "this is an opt-in role for receiving announcements about server updates, contests, etc. We will try to not overuse this to spam people with annoying updates, but each person's definition of \"annoying\" is different. The Hebrew means \"inform\" [leho'dia]."
  show_button: true
-
  type: "role"
  category: "Messaging Preferences"
  name: "DM Friendly | בסדר לשלח הודעות"
  id: "498208423524171796"
  color: "#7dff00"
  text: "this role is to signify that you are OK with receiving direct messages (DMs) from people on this server. The Hebrew means \"OK to send messages\" [beseder lishloakh hodaot]."
  show_button: true
-
  type: "role"
  category: "Messaging Preferences"
  name: "Ask To DM | שאל לפני לשלח הודעות"
  id: "498207388890038274"
  color: "#ffd200"
  text: "this role is to signify that you might be OK with receiving direct messages, if you are asked first and reply in the affirmative. The Hebrew means \"ask before sending messages\" [she'el lifney lishloakh hodaot]."
  show_button: true
-
  type: "role"
  category: "Messaging Preferences"
  name: "Do Not DM | לא לשלח הודעות"
  id: "498208466066866186"
  color: "#ff0000"
  text: "this role is to signify that you do not consent to receiving direct messages from anyone on this server, but please note that moderators may always message you for important communication, e.g. if you've broken a rule and disciplinary action needs to be taken against you. The Hebrew means \"do not send messages\" [lo lishloakh hodaot]."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Enby/Other | אנשים"
  id: "497568507601485836"
  color: "#0dcf4f"
  text: "this is the enby (short for non-binary) / catch-all role, for anyone who does not identify inside the binary gender boxes for whatever reason. The Hebrew means \"people\" [anashim]."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Feminine | נשים"
  id: "476916459470061569"
  color: "#e91e63"
  text: "this is the feminine gender identity role. The Hebrew literally means \"women\" [nashim]."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Masculine | גברים"
  id: "476916976011444244"
  color: "#1a7de5"
  text: "this is the masculine gender identity role. The Hebrew literally means \"men\" [gvarim]."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Pride | גאווה"
  id: "498828572325183489"
  color: "#aa32e6"
  text: "this role signifies that you identify under the LGBTQ+ umbrella. This role grants access to a role locked channel for discussing your LGBTQIA+ identity in a safe space. The Hebrew means \"pride\" [gav'ah]."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Plural | לא אחד"
  id: "501658770389336084"
  color: "#843da4"
  text: "this is a role for any plural members of the server, i.e. systems and any others experiencing a multiplicity of consciousnesses, for whatever reason. The Hebrew means \"not one\" [lo ekhad]."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Empath | אמפת"
  id: "497830688175685643"
  color: "#b8ffdf"
  text: "Empath"
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Psivamp | ערפד נפשי"
  id: "505446232005541889"
  color: "#1d1d2f"
  text: "for self-identified vampires who feed on psychic energy."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Sanguinarian | ערפד הדם"
  id: "505446530354774050"
  color: "#3d110a"
  text: "for self-identified vampires who feed on animal and/or human blood."
  show_button: true
-
  type: "role"
  category: "Identities"
  name: "Spoonie | כפיות"
  id: "504971274431496194"
  color: "#ff9960"
  text: "this is a role for anyone who identifies as a spoonie, which is a term for folks who experience chronic illness or some other situation that makes it difficult for them to function at times due to a limited reserve of energy (quantified as \"spoons\"). <a href=\"https://butyoudontlooksick.com/articles/written-by-christine/the-spoon-theory/\" target=\"_blank\">Click here</a> for more details on the spoons paradigm. The Hebrew means \"teaspoons\" [capiot]."
  show_button: true
